In [1]:
# Kornpob Bhirombhakdi
# kbhirombhakdi@stsci.edu

In [2]:
# don't forget to pip install axehelper
from axehelper.axehelper_confreader import AXEhelper_ConfReader
from axehelper.axehelper_computesip import AXEhelper_computeSIP


In [3]:
conffile = '/Users/kbhirombhakdi/_work/_calib_files/ACS.WFC/ACS.WFC.CHIP1.Cycle13.5.conf'


In [4]:
conf = AXEhelper_ConfReader(conffile)
conf.getbeam()
conf.beam


{'BEAM': 'A',
 'BEAMA': array(['-30', '160'], dtype='<U3'),
 'MMAG_EXTRACT_A': array(['27'], dtype='<U2'),
 'MMAG_MARK_A': array(['29'], dtype='<U2'),
 'DYDX_ORDER_A': array(['1'], dtype='<U1'),
 'XOFF_A': array(['0.0'], dtype='<U3'),
 'YOFF_A': array(['-0.7781', '-1.32E-5', '-2.79E-4', '1.345E-8', '1.516E-7',
        '-2.88E-9'], dtype='<U8'),
 'DISP_ORDER_A': array(['2'], dtype='<U1'),
 'DYDX_A_0': array(['0'], dtype='<U1'),
 'DYDX_A_1': array(['-0.03454', '2.100E-6', '-5.42E-6', '-2.0E-10', '2.75E-10',
        '1.92E-10'], dtype='<U8'),
 'DLDP_A_0': array(['4787.26', '0.003893', '-0.07142', '-8.06E-7', '5.226E-7',
        '3.040E-5'], dtype='<U8'),
 'DLDP_A_1': array(['37.3017', '0.00184', '-2.12E-4', '-1.14E-7', '-7.94E-8',
        '-3.94E-7'], dtype='<U8'),
 'DLDP_A_2': array(['0.005756', '-1.88E-6', '-4.89E-6', '7.21E-10', '-1.9E-10',
        '2.159E-9'], dtype='<U8')}

In [5]:
conf.make_coef2d()
conf.coef2d


{'DYDX_A_0': {'NORDER': 1, 'COEF': {(0, 0): 0.0}},
 'DYDX_A_1': {'NORDER': 3,
  'COEF': {(0, 0): -0.03454,
   (1, 0): 2.1e-06,
   (0, 1): -5.42e-06,
   (2, 0): -2e-10,
   (1, 1): 2.75e-10,
   (0, 2): 1.92e-10}},
 'DLDP_A_0': {'NORDER': 3,
  'COEF': {(0, 0): 4787.26,
   (1, 0): 0.003893,
   (0, 1): -0.07142,
   (2, 0): -8.06e-07,
   (1, 1): 5.226e-07,
   (0, 2): 3.04e-05}},
 'DLDP_A_1': {'NORDER': 3,
  'COEF': {(0, 0): 37.3017,
   (1, 0): 0.00184,
   (0, 1): -0.000212,
   (2, 0): -1.14e-07,
   (1, 1): -7.94e-08,
   (0, 2): -3.94e-07}},
 'DLDP_A_2': {'NORDER': 3,
  'COEF': {(0, 0): 0.005756,
   (1, 0): -1.88e-06,
   (0, 1): -4.89e-06,
   (2, 0): 7.21e-10,
   (1, 1): -1.9e-10,
   (0, 2): 2.159e-09}}}

In [6]:
import numpy as np

xref = np.array([400.])
yref = np.array([500.])
obj = AXEhelper_computeSIP(conf.coef2d,xref,yref)
obj.coef2d,obj.x1,obj.x2


({'DYDX_A_0': {'NORDER': 1, 'COEF': {(0, 0): 0.0}},
  'DYDX_A_1': {'NORDER': 3,
   'COEF': {(0, 0): -0.03454,
    (1, 0): 2.1e-06,
    (0, 1): -5.42e-06,
    (2, 0): -2e-10,
    (1, 1): 2.75e-10,
    (0, 2): 1.92e-10}},
  'DLDP_A_0': {'NORDER': 3,
   'COEF': {(0, 0): 4787.26,
    (1, 0): 0.003893,
    (0, 1): -0.07142,
    (2, 0): -8.06e-07,
    (1, 1): 5.226e-07,
    (0, 2): 3.04e-05}},
  'DLDP_A_1': {'NORDER': 3,
   'COEF': {(0, 0): 37.3017,
    (1, 0): 0.00184,
    (0, 1): -0.000212,
    (2, 0): -1.14e-07,
    (1, 1): -7.94e-08,
    (0, 2): -3.94e-07}},
  'DLDP_A_2': {'NORDER': 3,
   'COEF': {(0, 0): 0.005756,
    (1, 0): -1.88e-06,
    (0, 1): -4.89e-06,
    (2, 0): 7.21e-10,
    (1, 1): -1.9e-10,
    (0, 2): 2.159e-09}}},
 array([400.]),
 array([500.]))

In [7]:
obj.compress()
obj.coef1d


{'DYDX_A_0': array([0.]),
 'DYDX_A_1': array([-0.036339]),
 'DLDP_A_0': array([4760.68276]),
 'DLDP_A_1': array([37.79908]),
 'DLDP_A_2': array([0.00317611])}

# Sanity Check

In [8]:
# take DYDX_A_1
tmp = -0.03454 + 2.1e-06*xref + -5.42e-06*yref
tmp += -2e-10*xref**2 + 2.75e-10*xref*yref + 1.92e-10*yref**2
tmp


array([-0.036339])